version: '3.1'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
   
  back-end:
    image: node:latest
    container_name: back-end
    restart: always
    depends_on:
      - mysql
    env_file:
      - ./.env
    ports:
      - ${BACK_END_PORT}:${BACK_END_PORT}
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./back-end:/usr/app
    working_dir: /usr/app
    command: bash -c "npm install && npx sequelize db:migrate && npm run debug"
  
  front-end:
    image: node:14
    container_name: front-end
    restart: always
    depends_on:
      - back-end
    env_file:
      - ./.env
    ports:
      - ${FRONT_END_PORT}:${FRONT_END_PORT}
    # environment:
    #   BACK_HOST: back-end
    #   BACK_PORT: 3001
    volumes:
      - ./front-end:/usr/app
    working_dir: /usr/app
    command: bash -c "npm install && npm start"